### PR TITLE
Small edits to Comprehensions.

### PR DESCRIPTION
**Pull request by JoshMcCullough**
Tiny text fix and also fixed the last example as the result should have been squared (for clarity).

### CODE REVIEW

**Comment by yasoob** [comment]
I am not sure why my gut says that it should still be *anyone* but as English is not my first language I am happy to go with your suggestion. Thanks! :+1:

**Comment by JoshMcCullough** [comment]
"anyone" is used like: "Anyone can do it." It refers to a person. :)

**Comment by SanketDG** [comment]
"any one" would be correct too and would make more sense.

**Comment by JoshMcCullough** [comment]
Yes, I almost changed it to "any one" but thought it sounded redundant and figured "any" would suffice.

**Comment by eclutsk** [comment]
Thank you for the link.  I missed that thread of discussion.

**Comment by yasoob** [comment]
Thanks for clearing it up guys! :smile:

**Comment by JoshMcCullough** [comment]
Yeah, feel free to change it to "any one" -- both make sense.

**Pull request merged**
