### PR TITLE
Update decorators.rst

### PR DESCRIPTION
**Pull request by nbasu02**
Added a section on passing parameters into decorators, and decorators as classes.

I had a bit of trouble properly wording a few sections, so please check to make sure everything makes some sense.  I also feel a bit weird on two things and would like some input:

1. Should the topics of decorators with args and decorators as classes be separated?
2. I feel I dug myself into a corner with the logging example, and not actually implementing a function that would send an email (for obvious reasons) feels like a small blemish on the chapter.  Thoughts?

### CODE REVIEW

**Comment by yasoob** [comment]
Thanks :+1: Will take a look at this tomorrow :)

**Comment by nbasu02** [comment]
Bump

**Comment by yasoob** [comment]
I am extremely sorry for not replying before. I was/am extremely busy. I have taken a look at it. The tone and the way the content is written needs some revision. I would update you when I revise the content which you have written. 

And thanks for taking out some time to write this.

**Comment by nbasu02** [comment]
No worries, let me know when you need me to do a second pass.  But totally understood; I've never been the best writer.

**Comment by qpid** [comment]
There was an syntax error in the code example for 'Nesting a Decorator Within a Function', which also caused the syntax highlighting on the website to be disabled.

screen shot 2015-12-01 at 4 14 11 pm

I have submitted a pull request with the corrected code. https://github.com/yasoob/intermediatePython/pull/110

**Pull request merged**
